### ISSUE TITLE
scrollbar always persist

### ISSUE THREAD

**Issue by whitedogg13** [revtel/reactconf.tv#30]
As shown in following screenshot, the scrollbar always persist:

![image](https://user-images.githubusercontent.com/10307875/104331079-a24e6980-5529-11eb-87cd-740e6f6a3a42.png)

Previously on Mac, scrollbar is visible when user does scroll, otherwise it's hidden. However the scrollbar now always shown when overflow, make the page looks pretty ugly.

BTW, my Mac works weird recently, not sure whether this only happens on my machine. Are you guys able to reproduce this issue?

**Comment by guychienll** [comment]
No longer persist !
